ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl
ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl/sensor/laser_focus
ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl/sensor/laser_focus/vl6180_api/inc
ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl/sensor/laser_focus/show_lib/inc

obj-$(CONFIG_MSMB_CAMERA) += msm_laser_focus_vl6180_api.o
obj-$(CONFIG_MSMB_CAMERA) += vl6180x_i2c.o
obj-$(CONFIG_MSMB_CAMERA) += vl6180x_api.o
