ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl
ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl/sensor/laser_focus_zc550kl/show_lib/inc

obj-$(CONFIG_MSMB_CAMERA) += show_debug.o
