ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl
ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl/sensor/laser_focus/show_lib/inc
ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl/sensor/laser_focus/laura/inc

obj-$(CONFIG_MSMB_CAMERA) += laura_factory_func.o
#laura_factory_func-objs := libcalc_calib.a
obj-$(CONFIG_MSMB_CAMERA) += laura_shipping_func.o
