ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl
ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
