ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl
ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
