ifeq ($(IS_BOARD_PLATFORM), 8939)
ccflags-y += -DCONFIG_8939_CSIPHY
endif
ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl
ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl/sensor/io
obj-$(CONFIG_MSM_CSIPHY) += msm_csiphy.o
