ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl
ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_zc550kl/sensor/cci

obj-$(CONFIG_MSMB_CAMERA) += vl6180_api/
obj-$(CONFIG_MSMB_CAMERA) += show_lib/
obj-$(CONFIG_MSMB_CAMERA) += laura/
